#!/usr/bin/env bash
# Transfers a file from a client to my server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
